#!/bin/bash

if [ -z "$(which aria2c)" ]; then
    echo aria2c not found, install it:
    apt-get update
    apt-get install -y aria2 apt-utils
    echo
fi

apt-get update

# Use eval to enable lazy evaulation of the arguments
# Especially usefull when you are doing:
# 
#     curl pub_key | apt-key add -
#     echo deb url all main > /etc/apt/sources.list.d/a.list
#     apt-auto install -y '$(apt-cache search softwares-from-newly-added-mirror)'
exec apt-fast $(eval echo $@)
