# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * 1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    # 
    # The following code is adapted from:
    #     https://stackoverflow.com/questions/53208467/docker-hub-remtoe-build-triggers
    - name: Trigger docker hub auto build
      run: |
        curl -H "Content-Type: application/json" \
             --data '{"source_type": "Branch", "source_name": "master"}' \
             -X POST "https://hub.docker.com/api/build/v1/source/090c808b-0f52-417e-b06a-6b1239650237/trigger/c1c1adb5-3f48-433d-b529-768691656f58/call/"
